server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    # 不注册自己
    register-with-eureka: false
    # 表示自己是注册中心，不需要检索服务
    fetch-registry: false
    service-url:
      # Eureka Server 交互的地址查询服务和注册服务都依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
