server:
  port: 8401

spring:
  main:
    allow-circular-references: true
  application:
    name: cloud-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            username: nacos
            password: nacos
            server-addr: localhost:8848
            dataId: cloud-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
feign:
  sentinel:
    enabled: true